[package]
name = "vsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
mem = "0.5.0"
num = "0.4.0"
digest = "0.11.0-pre"
